f=open("./test.txt",'w')
print("filename:",f.name)
print("mode",f.mode)
print("isreadable:",f.readable())
print("iswriteable",f.writable())
f.write("DAV MODEL SCHOOL\n")
f.write("IIT KHARAGPUR\n")
print("isclosed",f.closed)
f.close()
print("isclosed",f.closed)
print("Data saved successfully")
